# Generated by Django 4.0.4 on 2022-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_my_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, verbose_name='Firstname')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Lastname')),
            ],
        ),
        migrations.CreateModel(
            name='MigrateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, verbose_name='Firstname')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Lastname')),
            ],
        ),
    ]
