# Generated by Django 4.0.4 on 2022-05-26 13:49

from django.db import migrations


def transfer_data(apps, schema_editor):
    Data = apps.get_model("mainapp", "Human")
    IntermediateModel = apps.get_model("mainapp", "MigrateModel")
    for i in Data.objects.all():
        IntermediateModel.objects.create(
            name=i.first_name,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_my_migration'),
    ]

    operations = [migrations.RunPython(transfer_data), ]
