# Generated by Django 4.0.4 on 2022-05-26 14:39

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0007_transfer_data_to_dest_model'),
    ]

    operations = [migrations.DeleteModel(
            name='MigrateModel',
        ), ]
