# Generated by Django 4.0.4 on 2022-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_intermediate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
